package view.enums;

public enum Validations {
    EMPTY_FIELD,
    INVALID_USERNAME,
    DUPLICATE_USERNAME,
    INVALID_FLAG,
    USERNAME_CHANGE_SUCCESSFUL,
    NICKNAME_CHANGE_SUCCESSFUL,
    EMAIL_CHANGE_SUCCESSFUL,
}
